-- ============================================================
-- 042_block_based_pages.sql
--
-- Block-based page composition for tenant websites — Gutenberg-style.
--
-- `home_blocks` is a JSONB array of { id, type, data } block records.
-- When set, the SSR renderer iterates blocks instead of laying out
-- flat config sections. When NULL/empty, falls back to the existing
-- per-section layout for backwards compat.
--
-- Block types (v1): hero, text, image, two_column, cta_strip,
--   gallery, menu_pdfs, allergens, opening_hours, find_us, contact,
--   booking_widget, divider, faq.
--
-- Each block has its own `data` shape — validated client-side by the
-- block registry, server-side accepted as opaque JSONB. The block id
-- is a UUID generated by the client (used by drag-reorder and React
-- keys); not a foreign key.
--
-- Custom pages (website_pages) get the same column for parity, so the
-- builder UI can target them later without another migration.
-- ============================================================

BEGIN;

ALTER TABLE website_config
  ADD COLUMN IF NOT EXISTS home_blocks jsonb;

ALTER TABLE website_pages
  ADD COLUMN IF NOT EXISTS blocks jsonb;

COMMIT;
