-- 064_fix_order_sheet_data.sql
-- SUPERSEDED — do not add logic here.
--
-- The original version of this file used TRUNCATE, which Postgres rejects
-- with "cannot truncate a table referenced in a foreign key constraint"
-- (the restriction is table-level, not row-level, so truncating children
-- first does not help). That aborted every deploy before migration 065
-- could run.
--
-- This file was never applied successfully, so it is safe to rewrite it as
-- a no-op. All cleanup + reseeding now lives in 065 using DELETE in
-- FK-safe order.
SELECT 1;
